### ISSUE TITLE
python 3 ?

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida-miseq-uploader#5]
""DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
""

**Comment by JeffreyThiessen** [comment]
We are moving to a new uploader that is built on python 3. This repo will stick around for now, but we won't be updating it to python 3. The new uploader has updated libraries and is more stable.

https://github.com/phac-nml/irida-uploader

**Comment by happykhan** [comment]
Please mention this repo is deprecated and maybe link to new one.

**Comment by JeffreyThiessen** [comment]
Once our 1.0 release of the new uploader is officially out, that will be done. We have one final stability release for this one coming yet too.
